### ISSUE TITLE
User story for posting a picture

### ISSUE THREAD

**Issue by gabjuteau** [gabjuteau/InstaFlex#1]

**Comment by LeClutch** [comment]
As a user I want to be able to post pictures on my page

**Comment by LeClutch** [comment]
As a user I want to be able to choose the album that I want to take a picture from.

**Comment by Yollaytl** [comment]
As a user, I want to add a specific filter to my picture before posting.

**Comment by Yollaytl** [comment]
As a user, I want to add multiple pictures to my post.
